export * from './babel';
export * from './eslint';
export * from './html';
export * from './licenses';
export * from './packageJson';
export * from './parcel';
export * from './readme';
export * from './tsconfig';
export * from './vscode';
